### ISSUE TITLE
[需求审计] 问卷可以增加统计功能

### ISSUE THREAD

**Issue by PJsFirst** [sysu-swsad-team/sysu-swsad-team.github.io#6]
发布者可以查看问卷的统计情况，这个需求有必要。

**Comment by Ernie1** [comment]
感谢关注，这个需求我们考虑了。因为我们的问卷用户可以设置限额，那当然需要统计了。而且我们的统计是考虑状态的，只统计进行中或已确认或已评价而不考虑取消的问卷。如果还有问题的话，欢迎随时再次打开issue。
